# Generated by Django 3.2.9 on 2021-11-10 05:37

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='content',
            field=wagtail.core.fields.StreamField([('service_details', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.RichTextBlock()), ('blog', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(Required=False)), ('description', wagtail.core.blocks.RichTextBlock()), ('date', wagtail.core.blocks.DateBlock())])))])), ('pricing_section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock(required=True)), ('description', wagtail.core.blocks.TextBlock(required=True)), ('card', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('card_title', wagtail.core.blocks.CharBlock()), ('price', wagtail.core.blocks.CharBlock()), ('list', wagtail.core.blocks.RichTextBlock()), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='ChoosePlan', max_length='50', required=True))])))]))], blank=True, null=True),
        ),
    ]
