# Generated by Django 3.2.9 on 2021-11-09 12:33

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('blog', '0002_bloglistingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='content',
            field=wagtail.core.fields.StreamField([('blog_detail', wagtail.core.blocks.StructBlock([('carousel', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('Title', wagtail.core.blocks.TextBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(Required=False)), ('description', wagtail.core.blocks.RichTextBlock()), ('date', wagtail.core.blocks.DateBlock())])))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='BlogListingPage',
        ),
    ]
