# Generated by Django 3.2.9 on 2021-11-06 10:52

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('about_area', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('subtitle', wagtail.core.blocks.RichTextBlock(required=True)), ('description', wagtail.core.blocks.CharBlock(max_length=150, required=True)), ('paragraph', wagtail.core.blocks.RichTextBlock(required=True)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn More', max_length='50', required=True))])), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
    ]
