# Generated by Django 3.2.9 on 2021-11-06 14:22

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0008_alter_homepage_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutArea',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('about_title', models.CharField(max_length=100)),
                ('about_subtitle', wagtail.core.fields.RichTextField()),
                ('about_description', models.CharField(max_length=100)),
                ('about_paragraph', wagtail.core.fields.RichTextField()),
                ('about_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
