# Generated by Django 3.2.9 on 2021-11-07 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_aboutarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='content',
            new_name='body',
        ),
    ]
