# Generated by Django 3.2.9 on 2021-11-07 06:49

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_content_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('about_area', wagtail.core.blocks.StructBlock([('about_title', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('about_subtitle', wagtail.core.blocks.RichTextBlock(required=True)), ('about_list1', wagtail.core.blocks.RichTextBlock(required=True)), ('about_list2', wagtail.core.blocks.RichTextBlock(required=True)), ('about_list3', wagtail.core.blocks.RichTextBlock(required=True)), ('about_description', wagtail.core.blocks.CharBlock(max_length=150, required=True)), ('about_paragraph', wagtail.core.blocks.RichTextBlock(required=True)), ('about_button_url', wagtail.core.blocks.URLBlock(required=False)), ('about_button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('about_button_text', wagtail.core.blocks.CharBlock(default='Learn More', max_length='50', required=True)), ('about_image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True),
        ),
    ]
