# Generated by Django 3.2.9 on 2021-11-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20211109_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='button_text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='button_url',
            field=models.URLField(null=True),
        ),
    ]
