# Generated by Django 3.2.9 on 2021-11-09 05:02

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20211109_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='button_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='button_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='button_url',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('about_area', wagtail.core.blocks.StructBlock([('about_title', wagtail.core.blocks.CharBlock(max_length=100, required=True)), ('about_subtitle', wagtail.core.blocks.RichTextBlock(required=True)), ('about_description', wagtail.core.blocks.CharBlock(max_length=150, required=True)), ('about_paragraph', wagtail.core.blocks.RichTextBlock(required=True)), ('about_button_url', wagtail.core.blocks.URLBlock(required=False)), ('about_button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('about_button_text', wagtail.core.blocks.CharBlock(default='Learn More', max_length='50', required=True)), ('about_image', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('fun_facts', wagtail.core.blocks.StructBlock([('fact', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('value', wagtail.core.blocks.IntegerBlock()), ('letter', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.TextBlock())])))])), ('features_Area', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock(required=True)), ('description', wagtail.core.blocks.TextBlock(required=True)), ('card', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('card_icon', wagtail.core.blocks.TextBlock(required=True)), ('card_title', wagtail.core.blocks.CharBlock()), ('card_desc', wagtail.core.blocks.RichTextBlock())])))])), ('carousel', wagtail.core.blocks.StructBlock([('carousel', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.TextBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(Required=False)), ('name', wagtail.core.blocks.TextBlock()), ('role', wagtail.core.blocks.TextBlock())])))])), ('pricing_section', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock(required=True)), ('description', wagtail.core.blocks.TextBlock(required=True)), ('card', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('card_title', wagtail.core.blocks.CharBlock()), ('price', wagtail.core.blocks.CharBlock()), ('list', wagtail.core.blocks.RichTextBlock()), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='ChoosePlan', max_length='50', required=True))])))])), ('Leftimagerightblock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('heading', wagtail.core.blocks.TextBlock()), ('description', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('apps', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(Required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='ChoosePlan', max_length='50', required=True))])))])), ('Rightimagerightblock', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=False)), ('heading', wagtail.core.blocks.TextBlock()), ('description', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('apps', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(Required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='ChoosePlan', max_length='50', required=True))])))]))], blank=True, null=True),
        ),
    ]
